community_api:
    resource: "@CommunityApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api_login_check:
    path: "/login_check"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

users:
  type: rest
  prefix: /api
  resource: Community\ApiBundle\Controller\UsersController